### PR TITLE
Update contribution information

### PR DESCRIPTION
**Pull request by serinamarie**
## Description

Uses our new contribution page in the docs to provide details on how to contribute

https://docs.prefect.io/recipes/contribute-recipes/

### CODE REVIEW

**Comment by ahuang11** [comment]
Looks good to me! My only suggestion is if https://docs.prefect.io/recipes/contribute-recipes/ also has these commands to help lower the friction / activation energy for the user to contribute. Also, I wonder if they need to first fork the repo?
```
git clone git@github.com:PrefectHQ/prefect-recipes.git
git branch feat/recipe-name
git checkout feat/recipe-name
```

**Review by ahuang11 — APPROVED** [review]

**Comment by serinamarie** [comment]
> Looks good to me! My only suggestion is if https://docs.prefect.io/recipes/contribute-recipes/ also has these commands to help lower the friction / activation energy for the user to contribute. Also, I wonder if they need to first fork the repo?
> 
> ```
> git clone git@github.com:PrefectHQ/prefect-recipes.git
> git branch feat/recipe-name
> git checkout feat/recipe-name
> ```

That's a good point. While the documentation doesn't have these commands laid out, I think it might be best to keep them here as well.

**Comment by ahuang11** [comment]
Maybe a PR to add these commands to the Prefect docs would help

**Comment by serinamarie** [comment]
> Maybe a PR to add these commands to the Prefect docs would help

They could add the commands to this section:
https://docs.prefect.io/recipes/contribute-recipes/#steps-to-adding-your-recipe

**Comment by serinamarie** [comment]
> Maybe a PR to add these commands to the Prefect docs would help

This was completed here: https://github.com/PrefectHQ/prefect/pull/8283

**Review by ahuang11 — APPROVED** [review]

**Pull request merged**
