### PR TITLE
Convert to mkdocs

### PR DESCRIPTION
**Pull request by ahuang11**
## Description

Start the migration to GitHub pages.

Here's what it looks like locally with `mkdocs serve`
image

Here's the one section I moved; could be more granular if we have more recipes
image

Eventually, I imagine these can be labeled with Collection tags like:
image

But instead of Experimental, can be (Ray, Dask, Azure, AWS, GCP etc)

Since I don't have Maintainer's permissions, I can't start the GitHub pages, but following these instructions will publish it:
"Upon publishing, a docs branch is automatically created. To hook this up to GitHub Pages, simply head over to https://github.com/PrefectHQ/prefect-recipes/settings/pages, select docs under the dropdown menu, keep the default /root folder, Save, and upon refresh, you should see a prompt stating "Your site is published at https://prefecthq.github.io/prefect-recipes". Don't forget to add this link to the repo's "About" section, under "Website" so users can access the docs easily."

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## New Recipe Checklist

- [ ] My PR is in the format of `Add <project-name> recipe`
- [ ] My recipe is reproducible and explains everything needed to run successfully. If my code has external dependencies, I make mention of them.
- [ ] My code is easily understandable and/or well-commented.
- [ ] If my recipe requires a new category (e.g. creating a monitoring/ folder in devops/), I have encapsulated my project within its own subfolder so that others can add their own recipes as well.
- [ ] If my recipe uses Prefect < 2.0, my code is within the prefect-v1-legacy/ folder.

### CODE REVIEW

**Comment by serinamarie** [comment]
I like this idea of having GitHub Pages! Just a few suggestions:

I would prefer to keep all of the recipes searchable/visible on the README. I know in collections there is no link to the GitHub Pages as it's meant to be accessed via the Prefect Docs, right? But I want anyone to find the recipes repo and have all the recipes at their fingertips. Only other thing I can think of is that there is a broken image on the README if you move the Chef Marvin image. 

With those little changes I think this would be good to go! Thanks a lot for putting this together :)

**Comment by ahuang11** [comment]
> I know in collections there is no link to the GitHub Pages as it's meant to be accessed via the Prefect Docs, right? 

Do you mean this?
image

**Comment by serinamarie** [comment]
> > I know in collections there is no link to the GitHub Pages as it's meant to be accessed via the Prefect Docs, right?
> 
> Do you mean this? image

Ah, I hadn't noticed that.

**Comment by ahuang11** [comment]
Sounds good to me.

I also wonder if there's a way to improve visibility for docs link.

**Review by serinamarie — APPROVED** [review]

**Pull request merged**
