### PR TITLE
script and docker storage

### PR DESCRIPTION
**Pull request by jeanluciano**

### CODE REVIEW

**Comment by jamiedick** [comment]
@jeanluciano are you still working on this?

**Comment by jamiedick** [comment]
@jeanluciano are you still working on this?

**Comment by jeanluciano** [comment]
> 
Yeah I'll get those changes in.

**Comment by serinamarie** [comment]
@jeanluciano Can you put this under `prefect-v1-legacy` folder and re-request review?

**Review by jamiezieziula — APPROVED** [review]

**Review by serinamarie — APPROVED** [review]

**Pull request merged**
