### PR TITLE
Prefect version

### PR DESCRIPTION
**Pull request by prefectcboyd**
Adds prefect main version (Prefect1 or Prefect2) to cloud service folders.
Once we GA, we can create / duplicate and tailor for Prefect2 leaving 1.0 intact as needed?

This just changes folder naming structure for AWS / Azure

### CODE REVIEW

**Comment by gabcoyne** [comment]
I'm good with this, would like @jamiedick to weigh in

**Comment by jamiedick** [comment]
i'm fine with this -- although I kind of like nesting in 2 separate directories (`prefect-1/`, `prefect-2/`) rather than by file name, but up to you!

**Comment by prefectcboyd** [comment]
I think that makes good sense, I can update that.

**Comment by prefectcboyd** [comment]
Updated with the suggested nesting:
aws/prefect-1 and aws/prefect-2
azure/prefect-1 and azure/prefect-2

**Pull request closed without merging**
