### PR TITLE
Add Prefect Docker deployments recipe

### PR DESCRIPTION
**Pull request by EmilRex**
## Description

This PR adds a recipe for using Docker with Prefect deployments. Notably, it covers how Docker images can be used as a storage layer.

Please check out the [README](https://github.com/PrefectHQ/prefect-recipes/blob/deployments-docker/devops/deployments/docker/README.md) for more information.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## New Recipe Checklist

- [x] My PR is in the format of `Add <project-name> recipe`
- [x] My recipe is reproducible and explains everything needed to run successfully. If my code has external dependencies, I make mention of them.
- [x] My code is easily understandable and/or well-commented.
- [x] If my recipe requires a new category (e.g. creating a monitoring/ folder in devops/), I have encapsulated my project within its own subfolder so that others can add their own recipes as well.
- [x] If my recipe uses Prefect < 2.0, my code is within the prefect-v1-legacy/ folder.

### CODE REVIEW

**Comment by serinamarie** [comment]
Hi @EmilRex, thanks for your contribution to prefect-recipes! I added some small nit picky suggestions. Otherwise, testing your recipe locally worked flawlessly ✨

**Comment by EmilRex** [comment]
> Hi @EmilRex, thanks for your contribution to prefect-recipes! I added some small nit picky suggestions. Otherwise, testing your recipe locally worked flawlessly ✨

Woohoo 🎉  Happy to hear that! Nit pick away!

**Comment by EmilRex** [comment]
@serinamarie Just realized I don't see the comments. Did you submit them already?

**Comment by serinamarie** [comment]
> @serinamarie Just realized I don't see the comments. Did you submit them already?

I did submit them 🤔  I'll message you to set up a huddle for this.

**Review by serinamarie — APPROVED** [review]

**Review by gabcoyne — APPROVED** [review]

**Pull request merged**
